version: "3.8"

networks:
  deltr:
    external: true

services:
  website:
    init: true
    container_name: maddex
    restart: unless-stopped
    networks:
      - deltr
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app