version: "3.8"

networks:
  anglo-internal:
    external: true

services:
    website:
        init: true
        container_name: personal-maddex
        restart: unless-stopped
        networks:
            - anglo-internal
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app